### ISSUE TITLE
Process variable: bug preventing adding patterns in the editor

### ISSUE THREAD

**Issue by mitchellghl** [bdcheck/Hive-Mechanic-Django#25]
(1) You cannot add any patterns to the "Process Cookie" card. also
(2)You cannot add cards to the "none of the above" option

**Comment by audaciouscode** [comment]
Fixed on workshop.hivemechanic.org.

**Comment by audaciouscode** [comment]
Just applied some new fixes. Please validate and close if it's looking good to you as well.

**Comment by bdcheck** [comment]
Sadly, M reports bug persists: " I cannot add a pattern in the editor when I am in the Hive Mechanic Workshop. It does not respond when I press the blue "Add Pattern" button.

**Comment by audaciouscode** [comment]
Give it a spin now. I found a few more issues with that card that were not in my testing environment.
